FROM alpine:3.22.1

ENV NODE_VERSION 22.16.0

RUN apk add \
    build-base \
    webkit2gtk-4.1-dev \
    gtk+3.0-dev \
    curl \
    wget \
    file \
    openssl \
    libayatana-appindicator-dev \
    librsvg \
    bash

RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y

ENV SHELL=/bin/sh
ENV ENV=/etc/profile
RUN echo "" > /etc/profile
RUN curl -fsSL https://get.pnpm.io/install.sh | sh -

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
ENV NVM_DIR /root/.nvm

RUN $NVM_DIR/nvm.sh && \
    nvm install 22.16.0 && \
    nvm alias default 22.16.0 && \
    nvm use default

CMD [ "sleep", "infinity" ]