services:
  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.dev
    container_name: srotalekh-backend
    env_file:
      - ./backend/template.env
    ports:
      - "8080:8080"
    command: sh -c "cd /app && ./build/srotalekh-backend"
    networks:
      - srotalekh-network
networks:
  srotalekh-network:
