FROM alpine:3.22.1

RUN apk add \
    cpprestsdk-dev \
    curl \
    bash \
    gdb \
    cmake \
    openssl-dev \
    zlib-dev \
    build-base \
    boost-dev \
    boost-build \
    git \
    websocket++ \
    nlohmann-json \
    openblas-dev

COPY ./backend /app

WORKDIR /app

RUN git init
RUN rm -rf /app/build
RUN rm -rf /app/libraries

RUN git submodule add https://github.com/ggml-org/whisper.cpp.git ./libraries/whisper.cpp
RUN git submodule add https://github.com/paullouisageneau/libdatachannel.git ./libraries/libdatachannel
RUN git submodule update --init --recursive

RUN cd libraries/libdatachannel && git checkout v0.23.2
RUN cd libraries/whisper.cpp && git checkout v1.7.6

RUN mkdir /models
RUN /app/libraries/whisper.cpp/models/download-ggml-model.sh tiny /models

ENTRYPOINT [ "bash", "/app/entrypoint.sh" ]

